name: Build and Deploy to IIS

on:
  push:
    branches:
      - master  # تأكد من استبدال هذا باسم الفرع الذي تريد استخدامه

jobs:
  build:
    runs-on: self-hosted  # تشغيل الوظائف على GitHub Runner المحلي

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.402'  # تأكد من استخدام الإصدار الصحيح

    - name: Restore dependencies
      run: |
        dotnet restore
        Write-Host "Dependencies restored successfully."

    - name: Build the project
      run: |
        dotnet build --configuration Release
        Write-Host "Project built successfully."

    - name: Publish the project
      run: |
        dotnet publish --configuration Release --output ./publish
        Write-Host "Project published successfully to ./publish."

    - name: List published files
      run: |
        Get-ChildItem -Recurse ./publish
        Write-Host "Listed files in the publish directory."
      shell: powershell

    - name: Deploy to IIS
      run: |
        $siteName = 'github_action'
        $publishPath = './publish'
        $iisPath = 'C:\inetpub\wwwroot\github_action'
    
        Write-Host "Stopping IIS application pool..."
        Stop-WebAppPool -Name $siteName
    
        Write-Host "Starting deployment to IIS..."
        try {
            # تأكد من حذف الملفات السابقة
            Remove-Item -Recurse -Force $iisPath\*
            Write-Host "Old files removed successfully."
        } catch {
            Write-Host "Error removing files: $_"
        }
    
        # نسخ الملفات الجديدة
        Copy-Item -Recurse -Force $publishPath\* $iisPath
        Write-Host "New files copied successfully."
    
        # إعادة تشغيل تطبيق IIS
        Start-WebAppPool -Name $siteName
        Write-Host "IIS application pool restarted successfully."
      shell: powershell  # استخدام Windows PowerShell

